apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: 1.26.3
clusterName: kubernetes
imageRepository: registry.local/k8s-p10
dns: {}
etcd:
  local:
    dataDir: /var/lib/podsec/u7s/etcd
    imageRepository: registry.local/k8s-p10
    serverCertSANs:
      - 10.96.0.1
      - 127.0.0.1
    peerCertSANs:
      - 10.96.0.1
    extraArgs:
      name: resign5stern
      initial-cluster: resign5stern=https://0.0.0.0:2380
      initial-cluster-state: new
      listen-client-urls: https://0.0.0.0:2379
      #advertise-client-urls: https://10.96.0.1:2379
      initial-advertise-peer-urls: https://0.0.0.0:2380
      listen-peer-urls: https://0.0.0.0:2380
      enable-v2: 'true'
apiServer:
  certSANs:
    - 127.0.0.1
  extraArgs:
    advertise-address: 10.96.0.1
    etcd-servers: https://127.0.0.1:2379
  timeoutForControlPlane: 4m0s
controllerManager:
  extraArgs:
    allocate-node-cidrs: 'true'
    cluster-cidr: 10.244.0.0/16
    service-cluster-ip-range: 10.96.0.0/12
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: "10.244.0.0/16" # --pod-network-cidr
controlPlaneEndpoint: 10.96.0.1:6443
scheduler: {}
