kind: JoinConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: kube-apiserver:6443
    #token: abcdef.0123456789abcdef
    #unsafeSkipCAVerification: true
  timeout: 5m0s
  #tlsBootstrapToken: abcdef.0123456789abcdef
nodeRegistration:
  criSocket: unix:///run/crio/crio.sock
  imagePullPolicy: IfNotPresent
  name: host-92
  taints: null

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: iptables
clientConnection:
  kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
conntrack:
  maxPerCore: 0
  tcpEstablishedTimeout: 0s
  tcpCloseWaitTimeout: 0s
