# kubectl -n kube-system get cm kubeadm-config -o yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: $U7S_APISERVER
    token: $U7S_TOKEN
    caCertHashes: $U7S_CACERTHASH
  timeout: 5m0s
nodeRegistration:
  criSocket: unix:///run/crio/crio.sock
  imagePullPolicy: IfNotPresent
  name: $host
  taints: null
controlPlane:
  localAPIEndpoint:
    advertiseAddress: U7S_EXTIP
    bindPort: 6443
  certificateKey: U7S_CERIFICATEKEY

# https://stackoverflow.com/questions/51126164/how-do-i-find-the-join-command-for-kubeadm-on-the-master
