kind: JoinConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
#caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: kube-apiserver:6443
    token: ${KUBEADM_TOKEN}
    caCertHashes:
  timeout: 5m0s
  #tlsBootstrapToken: abcdef.0123456789abcdef
nodeRegistration:
  criSocket: unix:///run/crio/crio.sock
  imagePullPolicy: IfNotPresent
  name: host-92
  taints: null
